name: 'Install JVMCI, set JAVA_HOME and clone Graal'
runs:
  using: "composite"
  steps:
    - name: Install JVMCI
      run: jt install jvmci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(jt install jvmci)" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Clone Graal
      run: jt mx sforceimports
      shell: bash
      working-directory: ${{ github.action_path }}

    # GR-35354: workaround issue when building libcxx for Sulong with cmake 3.22
    - name: Downgrade to CMake 3.21.4
      run: |
        wget --no-verbose https://github.com/Kitware/CMake/releases/download/v3.21.4/cmake-3.21.4-linux-x86_64.tar.gz
        tar -xzf cmake-3.21.4-linux-x86_64.tar.gz
        echo "$PWD/cmake-3.21.4-linux-x86_64/bin" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: cmake --version
      shell: bash
      working-directory: ${{ github.action_path }}
